### ISSUE TITLE
Unwrap of None when calling next on Rows

### ISSUE THREAD

**Issue by wspeirs** [duckdb/duckdb-rs#200]
As the title says, calling `next()` on `Rows` is panics because `.unwrap()` is called on a `None` option. I'm using the bundled feature to link against duckdb.

Here is a simple reproducer:

```
use anyhow::{anyhow, Context, Result};
use duckdb::{Connection, params};

fn main() -> Result<()> {
    let conn = Connection::open_in_memory()?;

    let create_stmt =
    r#"
        CREATE SEQUENCE seq;
        CREATE OR REPLACE TABLE test (
            id    INTEGER PRIMARY KEY DEFAULT NEXTVAL('seq'),
            a     VARCHAR NOT NULL,
        );
    "#;

    conn.execute_batch(create_stmt).context("creating table")?;

    let num_rows = conn.execute("INSERT INTO test (a) VALUES (?)", params!["test"]).context("inserting")?;

    println!("INSERTED: {}", num_rows);

    let mut stmt = conn.prepare("SELECT * FROM test").context("preparing")?;
    let mut rows = stmt.raw_query();

    let row = rows.next().context("getting next row")?
        .ok_or(anyhow!("NO ROW!"))
        .context("getting row")?;
    let a: u64 = row.get("a").context("getting value")?;

    println!("GOT: {}", a);

    Ok( () )
}
```

Here is the backtrace:

```
INSERTED: 1
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/wspeirs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-0.8.1/src/raw_statement.rs:70:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
   3: core::option::Option<T>::unwrap
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:935:21
   4: duckdb::raw_statement::RawStatement::result_unwrap
             at /home/wspeirs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-0.8.1/src/raw_statement.rs:70:9
   5: duckdb::raw_statement::RawStatement::row_count
             at /home/wspeirs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-0.8.1/src/raw_statement.rs:75:46
   6: duckdb::statement::Statement::row_count
             at /home/wspeirs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-0.8.1/src/statement.rs:285:9
   7: <duckdb::row::Rows as fallible_streaming_iterator::FallibleStreamingIterator>::advance
             at /home/wspeirs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-0.8.1/src/row.rs:224:39
   8: duckdb::row::Rows::next
             at /home/wspeirs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-0.8.1/src/row.rs:47:9
   9: test::main
             at ./src/main.rs:28:15
  10: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

The relevant code from `raw_statement.rs`:

```
    #[inline]
    pub fn result_unwrap(&self) -> ffi::duckdb_arrow {
        self.result.unwrap()
    }

    #[inline]
    pub fn row_count(&self) -> usize {
        unsafe { ffi::duckdb_arrow_row_count(self.result_unwrap()) as usize }
    }
```

**Comment by wangfenjin** [comment]
I can do that, but anyway your code will not work as you misuse the raw_query.

You can refer to the code here https://github.com/duckdb/duckdb-rs/blob/main/src/statement.rs#L683

**Comment by wangfenjin** [comment]
It's not recommended to use low level api if you are not sure what happened inside

**Comment by wspeirs** [comment]
Understood, so the options are to use the other non-raw query methods, or call `raw_execute` _before_ `raw_query`... thanks!
